name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: echo GITHUB_EVENT_NAME
        run: echo "GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME}"

      - name: echo GITHUB_EVENT_PATH
        run: echo "GITHUB_EVENT_PATH=${GITHUB_EVENT_PATH}"
